### ISSUE TITLE
FKiSS Editor errors out

### ISSUE THREAD

**Issue by myAphelion** [kisekae/UltraKiss#2]
When attempting to create a new event in the FKiSS editor, an internal error message is presented and a new event cannot be created.

![image](https://github.com/kisekae/UltraKiss/assets/168505223/7a6a4c2a-bb97-4aa8-9481-7b32cc636417)

**Comment by kisekae** [comment]
Thank you for reporting this issue.

The problem is corrected.  Install the UltraKiss 3.7.3 (update 3) release from GitHub.  The HelpAbout UltraKiss dialog for update 3 will show a build date of June 8, 2024.
